/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Before;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.mockito.Mockito.*;

public class BibliotecaAppTest {

    private BibliotecaApp bibliotecaApp;
    private ConsoleOutput output;

    @Before
    public void testSet() {
        output = mock(ConsoleOutput.class);
        bibliotecaApp = new BibliotecaApp(output);
    }

    @Test
    public void testPrintBookList() {
        bibliotecaApp.printBookList();
        String expectPrint = "Test-driven Development\n" +
                "Refactoring: Improving the Design of Existing Code\n" +
                "Head First Java\n" +
                "Core Java Volume I\n";

        verify(output,times(1)).print(expectPrint);
    }

    @Test
    public void shouldPrintBookListWithDetail() {
        bibliotecaApp.printBooksDetail();
        String expectPrint = "Book Name                                                             Author                                                                Year Published                                                        \n" +
                "Test-driven Development                                               Kent Beck                                                             2003                                                                  \n" +
                "Refactoring: Improving the Design of Existing Code                    Martin Fowler                                                         2012                                                                  \n" +
                "Head First Java                                                       Kathy Sierra, Bert Bates                                              2003                                                                  \n" +
                "Core Java Volume I                                                    Cay S. Horstmann                                                      2015                                                                  \n";

        verify(output, times(1)).print(expectPrint);
    }

    @Test
    public void shouldPrintMainMenu() {
        bibliotecaApp.printMainMenu();

        verify(output, times(1)).print("Main Manu:\n * 1. List Books\n * 0. exit");
    }

    @Test
    public void shouldShowInvalidMessage() {
        String expectPrint = "Select a valid option!";
        bibliotecaApp.printWrongInstructionMessage();

        verify(output, times(1)).print(expectPrint);
    }

    @Test
    public void testPrintQuitMessage() {
        String expectPrint = "Goodbye!";
        String actualPrint = bibliotecaApp.printQuitMessage();

        assertEquals(expectPrint, actualPrint);
    }

    @Test
    public void shouldPrintWelcomeMessage() throws Exception {
        bibliotecaApp.printWelcomeMessage();

        verify(output, times(1)).print("Welcome to Biblioteca\n------------------------------------------");
    }
}
