/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Before;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.verify;

public class BibliotecaAppTest {

    private BibliotecaApp bibliotecaApp;

    @Before
    public void testSet() {
        bibliotecaApp = new BibliotecaApp(new ConsoleOutput());
    }

    @Test
    public void testPrintWelcomeMessage() {
        String actualMessage = bibliotecaApp.printWelcomeMessage();

        assertEquals("Welcome to Biblioteca\n------------------------------------------", actualMessage);
    }

    @Test
    public void testPrintBookList() {
        String actualPrint = bibliotecaApp.printBookList();
        String expectPrint = "Test-driven Development\n" +
                "Refactoring: Improving the Design of Existing Code\n" +
                "Head First Java\n" +
                "Core Java Volume I\n";

        assertEquals(expectPrint,actualPrint);
    }

    @Test
    public void testPrintBookListWithDetail() {
        String actualPrint = bibliotecaApp.printBooksDetail();
        String expectPrint = "Book Name                                                             Author                                                                Year Published                                                        \n" +
                "Test-driven Development                                               Kent Beck                                                             2003                                                                  \n" +
                "Refactoring: Improving the Design of Existing Code                    Martin Fowler                                                         2012                                                                  \n" +
                "Head First Java                                                       Kathy Sierra, Bert Bates                                              2003                                                                  \n" +
                "Core Java Volume I                                                    Cay S. Horstmann                                                      2015                                                                  \n";

        assertEquals(expectPrint, actualPrint);
    }

    @Test
    public void testShowMainMenu() {
        String actualPrint = bibliotecaApp.printMainMenu();
        String expectPrint = "Main Manu:\n * 1. List Books\n * 0. exit";

        assertEquals(expectPrint, actualPrint);
    }

    @Test
    public void testShowInvalidMessage() {
        String expectPrint = "Select a valid option!";
        String actualPrint = bibliotecaApp.printWrongInstructionMessage();

        assertEquals(expectPrint, actualPrint);
    }

    @Test
    public void testPrintQuitMessage() {
        String expectPrint = "Goodbye!";
        String actualPrint = bibliotecaApp.printQuitMessage();

        assertEquals(expectPrint, actualPrint);
    }

    @Test
    public void shouldPrintOutSth() throws Exception {
        ConsoleOutput output = mock(ConsoleOutput.class);
        BibliotecaApp bibliotecaApp = new BibliotecaApp(output);

        verify(output).print("welcome message!");
    }
}
